"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""


from dotenv import load_dotenv

from split_settings.tools import include
import logging

load_dotenv()

include('components/base.py', 'components/database.py', 'components/local.py')

logger = logging.getLogger(__name__)
