# Generated by Django 3.2 on 2022-06-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.RemoveField(model_name='filmwork', name='certificate',),
        migrations.RemoveField(model_name='filmwork', name='file_path',),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='film_work',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.filmwork',
                verbose_name='Film Work',
            ),
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='genre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.genre',
                verbose_name='Genre',
            ),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='film_work',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.filmwork',
                verbose_name='Film Work',
            ),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='movies.person',
                verbose_name='Person',
            ),
        ),
    ]
