# Generated by Django 3.2 on 2022-06-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmWorks',
            new_name='FilmWork',
        ),
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelTable(
            name='filmwork',
            table="content'.'film_work",
        ),
        migrations.AlterModelTable(
            name='genre',
            table="content'.'genre",
        ),
    ]
