# Generated by Django 3.2 on 2022-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_reduce_film_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='file_path'),
        ),
    ]
