# Generated by Django 3.2 on 2022-06-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_compare_with_sqlite_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
