# Generated by Django 3.2 on 2022-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reduce_gender_into_person_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['film_work', 'genre'], name="content'.'g_film_wo_eea05f_idx"),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['film_work', 'person', 'role'], name="content'.'p_film_wo_72ace6_idx"),
        ),
    ]
