# Generated by Django 3.2 on 2022-06-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220602_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'Действующее лицо', 'verbose_name_plural': 'Действующие лица'},
        ),
    ]
