# Generated by Django 3.2 on 2022-06-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_personfilmwork_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Действующее лицо', 'verbose_name_plural': 'Действующие лица'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={},
        ),
    ]
